# -*- coding: utf-8 -*-
"""Forecasting.Task

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F5kxQHzeMlKIWpGXJdT0QvQ3tTNKf-1w
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

a = pd.read_csv("/content/city_temperature.csv")
print(a)

print(a.head())

print("columns in dataset: ")
a.columns = a.columns.str.strip()


print(a.info())

print(a.shape)

print(a.isnull().sum)

a = a.dropna(subset=['AvgTemperature'])

a =a[a['AvgTemperature'] != -99]

a= a.reset_index(drop=True)

#after cleaning
print(a.head())
print(a.shape)

a.columns = a.columns.str.strip()


a['Year'] = pd.to_numeric(a['Year'], errors='coerce')
a['Month'] = pd.to_numeric(a['Month'], errors='coerce')
a['Day'] = pd.to_numeric(a['Day'], errors='coerce')

a['Date'] = pd.to_datetime(
    {
        'year': a['Year'],
        'month': a['Month'],
        'day': a['Day']
    },
    errors='coerce'
)


print(a[['Year', 'Month', 'Day', 'Date']].head())

print(a['City'].unique()[:20])

city_a=a[a['City']==
         'Rabat'].copy()
print(city_a.head())
print("Number of records:",len(city_a))

city_a = city_a.sort_values('Date')

city_a = city_a.dropna(subset=['Date', 'AvgTemperature'])


city_a = city_a[['Date', 'AvgTemperature']]


city_a = city_a.reset_index(drop=True)


print(city_a.head(10))

print("total recordsf:",len(city_a))
print(city_a.tail())

plt.figure(figsize=(12, 5))

plt.plot(city_a['Date'], city_a['AvgTemperature'])

plt.xlabel('Date')
plt.ylabel('Average Temperature')
plt.title('City Temperature Over Time')

plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

split = int(len(city_a) * 0.8)

train = city_a[:split]

test = city_a[split:]

print("Training records:", len(train))
print("Testing records:", len(test))

print("\nTraining data:")
print(train.head())

print("\nTesting data:")
print(test.head())

train = train.copy()
test = test.copy()

train['Year'] = train['Date'].dt.year
train['Month'] = train['Date'].dt.month
train['Day'] = train['Date'].dt.day

test['Year'] = test['Date'].dt.year
test['Month'] = test['Date'].dt.month
test['Day'] = test['Date'].dt.day

print(train.head())

X_train = train[['Year', 'Month', 'Day']]
y_train = train['AvgTemperature']

X_test = test[['Year', 'Month', 'Day']]
y_test = test['AvgTemperature']

print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)
print("X_test shape:", X_test.shape)
print("y_test shape:", y_test.shape)

from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X_train, y_train)

print("Model training completed successfully!")

y_pred = model.predict(X_test)

print("Predicted temperatures:")
print(y_pred[:10])

from sklearn.metrics import mean_absolute_error, mean_squared_error

mae = mean_absolute_error(y_test, y_pred)

rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print("Mean Absolute Error (MAE):", mae)
print("Root Mean Squared Error (RMSE):", rmse)

plt.figure(figsize=(12, 5))

plt.plot(test['Date'], y_test.values, label='Actual Temperature')
plt.plot(test['Date'], y_pred, label='Predicted Temperature')

plt.xlabel('Date')
plt.ylabel('Temperature')
plt.title('Actual vs Predicted Temperature')
plt.legend()

plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

last_date = city_a['Date'].max()

future_dates = pd.date_range(
    start=last_date + pd.Timedelta(days=1),
    periods=7,
    freq='D'
)

future_data = pd.DataFrame({
    'Year': future_dates.year,
    'Month': future_dates.month,
    'Day': future_dates.day
})

future_predictions = model.predict(future_data)

forecast = pd.DataFrame({
    'Date': future_dates,
    'Predicted_Temperature': future_predictions
})

print("Future Temperature Forecast:")
print(forecast)

plt.figure(figsize=(10, 5))

plt.plot(
    forecast['Date'],
    forecast['Predicted_Temperature'],
    marker='o'
)

plt.xlabel('Date')
plt.ylabel('Predicted Temperature')
plt.title('7-Day Temperature Forecast')

plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

