# -*- coding: utf-8 -*-
"""ML Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AynvZ2I7VSii-HeUpKw68c3IlsN5bXye
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#load datset
a=pd.read_csv("/content/plant_growth_data.csv")
print(a)

a.head()

a.tail()

print(a.columns)

print(a.info())

#check missing values
print(a.isnull().sum())

print(a.duplicated().sum())

print(a.dtypes)

#check unique values
print("SOIL TYPES : ")
print(a['Soil_Type'].unique())
print("WATER FREQUENCY : ")
print(a['Water_Frequency'].unique())
print("FERTILIZER TYPE : ")
print(a['Fertilizer_Type'].unique())

#Numerical Data Summary
print(a[['Sunlight_Hours','Temperature','Humidity','Growth_Milestone']].describe())

# Target Distribution
print(a['Growth_Milestone'].value_counts())

print(a.shape)

#seperate input & output
X=a.drop(['Growth_Milestone'],axis=1)
y=a['Growth_Milestone']

print("features : ")
print(X.head())
print("target : ")
print(y.head())

categorical_columns =['Soil_Type','Water_Frequency','Fertilizer_Type']

numerical_columns=['Sunlight_Hours','Temperature','Humidity']

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

#creating preprocessor
preprocessor=ColumnTransformer(
    transformers=[
        ('categorical',OneHotEncoder(handle_unknown = 'ignore'),categorical_columns),

         ('numerical','passthrough',numerical_columns)
         ]
)

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(X,y,
  test_size=0.2,random_state=42,stratify=y)

print("x_train:",x_train.shape)
print("x_test:",x_test.shape)
print("y_train:",y_train.shape)
print("y_test:",y_test.shape)

# Model building
from sklearn . ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators=100,random_state=42)

from sklearn.pipeline import Pipeline

model = Pipeline([
    ('preprocessor',preprocessor),
    ('classifier',RandomForestClassifier(n_estimators=100,random_state=42))
])

model.fit(x_train,y_train)

#model validation
y_pred = model.predict(x_test)
print(y_pred)

from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

# Accuracy
accuracy = accuracy_score(y_test,y_pred)
print("Accuracy :",accuracy)

#Classification Report
print("Classification Report :")
print(classification_report(y_test,y_pred))

# Confusion Matrix
cm = confusion_matrix(y_test,y_pred)
print("Confusion Matrix :")
print(cm)

# Graph
plt.figure(figsize=(10,6))
sns.heatmap(cm,
            annot=True,fmt='d',
  xticklabels=['No Growth','Growth'],
  yticklabels=['No Growth','Growth'],cmap='Blues')
plt.title('Confusion Matrix - PLANT GROWTH PREDICTION')
plt.xlabel('Predicted ')
plt.ylabel('Actual')
plt.show()

# Get Input From User
Soil =input("Enter Soil Type : ")
Water =input("Enter Water Frequency : ")
Fertilizer =input("Enter Fertilizer Type : ")
Sunlight =float(input("Enter Sunlight Hours : "))
Temperature =float(input("Enter Temperature : "))
Humidity =float(input("Enter Humidity : "))

# Dataframe
user_input = pd.DataFrame({
    'Soil_Type':[Soil],
    'Water_Frequency':[Water],
    'Fertilizer_Type':[Fertilizer],
    'Sunlight_Hours':[Sunlight],
    'Temperature':[Temperature],
    'Humidity':[Humidity]
})

# Predict
prediction = model.predict(user_input)

if prediction[0] == 1:
  print("prediction:  Plant will reach the milestone")
else:
    print("prediction: Plant will not reach the milestone")

#probability
probability = model.predict_proba(user_input)
print("GROWTH PROBABILITY: ",probability[0][1]*100,"%")

# 1.Growth Milestone Distribution
import matplotlib.pyplot as plt
a['Growth_Milestone'].value_counts().plot(kind='bar')
plt.title('Plant Growth Milestone Distribution')
plt.xlabel('Growth Milestone')
plt.ylabel('Number of Plants')
plt.xticks([0,1], ['No Growth','Growth'],rotation=0)
plt.show()

#2.Sunlight Hours vs Plant Growth(scatter plot)
plt.figure(figsize=(10,6))
sns.scatterplot(x='Sunlight_Hours',y='Growth_Milestone',data=a,hue='Growth_Milestone')
plt.title('Sunlight Hours vs Plant Growth')
plt.xlabel('Sunlight Hours')
plt.ylabel('Growth Milestone')
plt.show()

# boxplot
plt.figure(figsize=(8,5))
sns.boxplot(x='Growth_Milestone',y='Sunlight_Hours',data=a)
plt.title('Sunlight Hours vs Plant Growth')
plt.xlabel('Growth Milestone')
plt.ylabel('Sunlight Hours')
plt.xticks([0,1], ['No Growth','Growth'])
plt.show()

#3.Temperature vs Plant Growth
plt.figure(figsize=(10,6))
sns.boxplot(x='Growth_Milestone',y='Temperature',data=a)
plt.title('Temperature vs Plant Growth')
plt.xlabel('Growth Milestone')
plt.ylabel('Temperature')
plt.xticks([0,1], ['No Growth','Growth'])
plt.show()

# 4.Sunlight vs Temperature
plt.figure(figsize=(8,5))
plt.scatter(a['Sunlight_Hours'],a['Temperature'],c=a['Growth_Milestone'],cmap='coolwarm')
plt.title('Sunlight vs Temperature')
plt.xlabel('Sunlight Hours')
plt.ylabel('Temperature')
plt.show()

#5.Humidity vs Plant Growth
plt.figure(figsize=(10,6))
plt.scatter(a['Humidity'],a['Growth_Milestone'],c=a['Growth_Milestone'],cmap='coolwarm')
plt.title('Humidity vs Plant Growth')
plt.xlabel('Humidity')
plt.ylabel('Growth Milestone')
plt.show()

